Iter5
matvenick/go-url-shortener pull request #5
Opened 2023-12-13 00:32 UTC by matvenick

с пакетом os

2023-12-13 19:13 UTC, rktkov requested changes
Жду деталей реализации. Каркас выглядит нормально.

2023-12-13 19:13 UTC, rktkov commented on internal/app/server/server.go
> +	"go-url-shortener/internal/app/config"
Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2023-12-13 19:13 UTC, rktkov commented on internal/app/server/server.go
> +	// ...
Не информативные комментарии удаляем.

2023-12-13 19:13 UTC, rktkov commented on internal/app/config/config.go
> +func (c *Config) LoadFromFlags(serverAddress, baseURL string) {
Не думаю, что метод понадобится вне пакета, потому его стоит сделать закрытым.

2023-12-19 15:07 UTC, matvenick commented
> Жду деталей реализации. Каркас выглядит нормально.

@rktkov правильно понимаю, что не зря я задался вопросом, а где собственно сам синтаксис ссылки готовой, на каком домене ее делать, где хранить, почему не было такой задачи :D я честно думал это дальше где-то будет. Допиливать? Правильно понимаю, что нужно где-то БД развернуть, приобрести домен или еще как-то? Прошу простить тупые вопросы, вот пишу и самому максимально тупо...

2023-12-19 15:08 UTC, matvenick commented on internal/app/config/config.go
> +func (c *Config) LoadFromFlags(serverAddress, baseURL string) {
@rktkov а насколько нормально, что я сходу не понял, что такое "закрытый"? Имеется в виду в другой package перенести его?

2023-12-25 15:11 UTC, rktkov approved these changes

2024-10-14 16:30 UTC, merged